In [1]:
!pip install scipy

## EE4414 Quiz (Backpropagation)

### Name: HO YINGJIE         

### Matriculation Number: U1621969K

### import necessary libraries

In [2]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.utils.validation import column_or_1d
import matplotlib.pyplot as plt
import cv2
import scipy.io
import pickle

### read dataset

In [3]:
mat = scipy.io.loadmat('/raid1/p3/jiahui/yingjie/EE4414 folder/group3_train.mat')

### display headers of dataset

In [4]:
mat.keys()

dict_keys(['__header__', '__version__', '__globals__', 'test_data', 'train_data', 'train_labels'])

### checking the size of the training data & labels

In [5]:
mat['train_data'].shape

(10000, 3072)

In [6]:
mat['train_labels'].shape

(10000, 1)

### inspecting the training data & labels

In [7]:
mat['train_data']

array([[ 26,  17,  13, ...,  27,  26,  27],
       [ 94, 101,  95, ..., 182, 184, 155],
       [183, 158, 166, ..., 250, 250, 250],
       ...,
       [175, 200, 207, ..., 124,  49,  32],
       [ 28,  59,  67, ...,  36,  44,  41],
       [ 62,  40,  61, ..., 127, 124, 116]], dtype=uint8)

In [8]:
mat['train_labels']

array([[9],
       [6],
       [1],
       ...,
       [4],
       [8],
       [2]], dtype=uint8)

### checking the size of the testing data

In [9]:
mat['test_data'].shape

(1996, 3072)

In [10]:
label = column_or_1d(mat['train_labels'], warn=True)

/raid1/p3/jiahui/fyp_jiahui/lib/python3.6/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


### split data into training and validation set

In [11]:
X_train, X_test, y_train, y_test = train_test_split(mat['train_data'], mat['train_labels'],  train_size=0.7, shuffle=True, random_state=42)

### initialising the BP algorithm
#### - using Multi-layer perceptron classifer (MLPClassifier)

In [12]:
clf = MLPClassifier(activation='relu', solver='adam', hidden_layer_sizes=(250, 300, 250))

### training the MLPClassifier

In [13]:
clf.fit(X_train, y_train)

/raid1/p3/jiahui/fyp_jiahui/lib/python3.6/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(250, 300, 250), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

### predicting the validation data

In [14]:
prediction = clf.predict(X_test)
print(prediction)

[10  8  7 ...  4  9 10]


### obtaining accuracy score of validation

In [15]:
clf.score(X_test, y_test)

0.34833333333333333

### test on unseen data

In [16]:
mattest = scipy.io.loadmat('/raid1/p3/jiahui/yingjie/EE4414 folder/group3_test.mat')

In [17]:
save_model = "model_bp.sav"
pickle.dump(clf, open(save_model, 'wb'))

In [18]:
pkl_model = pickle.load(open(save_model, 'rb'))

In [19]:
score = pkl_model.score(mat['test_data'], mattest['test_labels'])
print('accuracy score: ', (score * 100), '%')

accuracy score:  34.66933867735471 %
